### ISSUE TITLE
Docs a little unclear for novices like me.

### ISSUE THREAD

**Issue by cparker4486** [devblackops/watchmen#9]
I'm looking forward to using your module but I some things clarified.
1. Where does 'myapp.watchmen.ps1' go? Does that go in the root of the MyAppOVF module folder?
2. What is the purpose of `WatchmenTest 'SystemOVF'` at the end of the example file? Is that demonstrating some kind of dependency? Or just simply a demonstration of how one Watchmen definition file can be used to test multiple OVF modules? If so, this doesn't seem very PowerShell-y to me. For example, I would expect something more like `Invoke-Watchmen -OVFModule MyAppOVF -WatchmenDefinition MyApp.Watchmen.ps1`.

Again, really looking forward to using this! I hope my feedback is valuable to you.

**Comment by devblackops** [comment]
I agree, the documentation could use some work. That's a side effect of the same person writing the module and documentation.
1. The `myapp.watchmen.ps1` file can go wherever makes sense for you in your environment. It just holds the definitions for what test modules and notifiers to execute.
2. The second `WatchmenTest` block was attempting to show that you can define more than one module to execute in the same file. Each `WatchmenTest` block can have it's own set of notifiers to execute in addition to the ones defined in `WatchmenOptions`.

Defining things this way (using a DSL) isn't very PowerShell-y, I agree. Part of this was my desire to experiment with creating DSLs and providing a framework for someone who isn't very experienced with PowerShell to create tests for their systems.

I like your example of using `Invoke-Watchmen` and providing the module(s) to execute inline. It wouldn't be too much work to add a parameter set to `Invoke-Watchmen` to work that way. Additional qualifiers on what / how to execute the test module (version, type, test, fromsource, parameters, and notifiers would be optional parameters you could pass in). Of course, once you start adding all those, your block of code wouldn't look too different than the example below.

``` powershell
WatchmenTest 'MyAppOVF' {
    version 1.0.0
    type 'Simple'
    test 'Storage.Capacity'
    fromSource 'PSGallery'
    parameters {
        FreeSystemDriveThreshold = 40000
    }
    notifies {
        logfile '\\fileserver01.mydomain.tld\monitoringshare\#{computername}.log' -when 'always'
    }
}
```

The feedback is always valuable! I'm always eager to hear about how people are using my projects. Without that, the projects don't really improve and I just end up talking to myself 😄

**Comment by cparker4486** [comment]
I'm assuming I'm just missing something but I've yet to get this to work. I've created a watchmen script with minimal configuration.

```
WatchmenOptions {
    notifies {
        email @{
            fromAddress = 'watchmen@domain.com'
            smtpServer = 'smtp.domain.local'
            port = 25
            subject = 'Watchmen alert - #{computername} - [#{test}] failed!'
            to = 'cparker@domain.com'
        }
    }
}

#WatchmenTest 'DNS' {
WatchmenTest 'OVF.Active.Directory' {
    # type 'DNS\Diagnostics\Simple'
    # type 'Diagnostics\Simple'
    type 'Simple'
}
```

You can see that I've tried a few different things (some of them just guesses) but I'm only getting errors.

The modules themselves live in a completely different directory than what is being complained about below. But `watchmen.ps1` _does_ live in that path.

```
type : Cannot find path 'C:\Users\cparker.domain\OneDrive - domain\PsScripts\Operation Validation Framework Tests\Simple' because it does not exist.
At C:\Users\cparker.domain\OneDrive - domain\PsScripts\Operation Validation Framework Tests\watchmen.ps1:38 char:5
+     type 'Simple'                   # Valid values 'simple', 'compreh ...
+     ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\cparke...rk Tests\Simple:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

Why is Watchmen looking for `Simple` in the same folder that `watchmen.ps1` lives in?

**Comment by devblackops** [comment]
I see the problem. It's an error in my example. The parameter to specify the type of OVF test to execute (simple or comprehensive) is **TestType**. In PowerShell, `type` is a built-in alias for `Get-Content` so I didn't want to use that as the function name. 

``` powershell
WatchmenTest 'OVF.Active.Directory' {
    type 'Simple'      # BAD <-type is a built-in alias for Get-Content
    testType 'Simple'  # GOOD
}
```

Sorry about the error. I hope you weren't pulling your hair out on that one. I'll correct the example in the readme.

**Comment by cparker4486** [comment]
OK I've got it running now.

I had to run `Import-Module` a few times to let it fail and tell me which prereq modules I was missing (psslack, posh-syslog) and then install those. After that it was able to load properly. However, I wonder if there's a way for you to improve this process? (I don't know if there is.)

Watchmen is in my module path but when I opened PowerShell it didn't complain about missing modules. Might it be possible to alert for missing prereqs at that time?

That brings up another point for the docs: a section on prerequisites. And going further, instructions on actually installing it. I downloaded the ZIP and copied the module folder. Remember my novice status. :) Even doing _that_ took me a bit of trial and error.

All in all I've learned a lot about PowerShell and working with modules.

**Comment by devblackops** [comment]
Installing the module via the PowerShell gallery will take care of installing the dependent modules. I'll update the README to include a section on the best way of installing.

If you have Windows 10, PowerShell 5 or the PowerShellGet module installed, you can run the following to install the module from the [PowerShell Gallery](https://www.powershellgallery.com/GettingStarted?section=Get%20Started).

``` powershell
Install-Module -Name Watchmen
```

**Comment by devblackops** [comment]
I've updated the README to include a section on installation and prerequisites.

https://github.com/devblackops/watchmen#installation
